### ISSUE TITLE
application state being called from background thread

### ISSUE THREAD

**Issue by romk1n** [amplitude/Amplitude-iOS#147]
We getting this warning in the log can you guys check your code? 

```Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]```

**Comment by djih** [comment]
@romk1n thanks for reporting. What version of the SDK are you on?

**Comment by TimothyDavidW** [comment]
Hi I am also experiencing this on 4.0.1 after updating to ios11.

Backtrace:
4   Amplitude_iOS                       0x000000010537c8f4 -[Amplitude initializeApiKey:userId:setUserId:] + 684
5   Amplitude_iOS                       0x000000010537c580 -[Amplitude initializeApiKey:] + 84

line 480 in the amplitude.m is where this is occurring.

**Comment by romk1n** [comment]
@djih sorry missed your message it is latest and previous version. Thanks.

**Comment by danielgalasko** [comment]
Any update on this? Its actually crashing our CI now for some reason

**Comment by djih** [comment]
@danielgalasko @romk1n I have a fix on a branch. I've tested it myself in our demo app but if you guys have a chance can you test it out? To install via Cocoapods: `pod 'Amplitude-iOS', :git => 'https://github.com/Amplitude/Amplitude-iOS.git', :branch => 'main-thread-violation'`. Otherwise I will just merge it and release a new version EOD today, thanks

**Comment by djih** [comment]
This is fixed with [v4.0.2](https://github.com/amplitude/Amplitude-iOS/releases/tag/v4.0.2) thanks!

**Comment by danielgalasko** [comment]
awesome stuff!!! Thanks for the release @djih 🙌

**Comment by romk1n** [comment]
@djih thanks, I just tried new version and still receiving the warning ```[reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]```

**Comment by djih** [comment]
@romk1n do you have more information like stack trace? When investigating the issue I was able to reproduce the warning in our iOS Demo app, and I verified that the fix stops the warning.
