### ISSUE TITLE
iOS 9 Deprecations

### ISSUE THREAD

**Issue by jeffexemine** [amplitude/Amplitude-iOS#67]
In the Amplitude.m file, there are two methods in use that have been deprecated since iOS 9. The first is `CFURLCreateStringByAddingPercentEscapes` and the second is `sendAsynchronousRequest:queue:completionHandler:`. I just wanted to bring these to your attention, and hopefully get some updates to remove the use of these deprecated methods.

**Comment by djih** [comment]
@jeffexemine  thank you for bringing this to our attention!

**Comment by nikolaenkoag** [comment]
Will there be updates to remove the use of these deprecated methods?

**Comment by Volcore** [comment]
This is a blocker, any updates on this?

**Comment by djih** [comment]
@Volcore how big of a blocker? I know the methods are deprecated but the functionality is still there

**Comment by Volcore** [comment]
it does not compile for iOS 11 on Xcode 9 Beta 4. I had to manually replace the functions myself, but I'm not very confident that it is functioning correctly and rather have an official working version.

**Comment by Volcore** [comment]
Currently receiving this error once i start adding parameters to events:

ERROR: Connection response received:400, bad_checksum

It happens in one of the deprecated functions i had to replace, so it seems likely to be related. Please advise.

**Comment by djih** [comment]
@Volcore what parameters are you adding to events? I'm currently pretty busy but I might have time later this week to replace the deprecated methods

**Comment by Volcore** [comment]
It's an NSDictionary with string -> string and string -> nsnumber mappings.

**Comment by bradmill** [comment]
I have l raised an online ticket for this as well, so would appreciate the calls been updated officially. Many thanks

**Comment by djih** [comment]
Just a quick update, I have  WIP branch here: https://github.com/amplitude/Amplitude-iOS/tree/replace-deprecated-methods. I've replaced the 2 deprecated methods and updated the unit tests. I'm still working on updating the SSL pinning logic but feel free to test what I have so far if you don't need SSL pinning.

**Comment by Volcore** [comment]
Still getting an issue on that branch:

![screen shot 2017-08-15 at 16 56 37](https://user-images.githubusercontent.com/95790/29321466-c986bbea-81da-11e7-944a-e916cb69bd45.png)

**Comment by djih** [comment]
@Volcore ah yea I think we can get rid of the ARC logic around the url encoding. I pushed an update to the branch

**Comment by Volcore** [comment]
Still getting the "ERROR: Connection response received:400, bad_checksum" when I'm trying to send the following dict:

Code:
```
  NSLog(@"%@ %@", @(name), dict);
  [[Amplitude instance] logEvent:@(name) withEventProperties:dict];
```

Log:
```
gacha {
    "currency_0" = 63;
    "currency_1" = 0;
    name = Gold;
    "num_rarity_0" = 9;
    "num_rarity_1" = 2;
    "num_rarity_2" = 0;
    "num_rarity_3" = 0;
    "num_rarity_stacks_0" = 2;
    "num_rarity_stacks_1" = 1;
    "num_rarity_stacks_2" = 0;
    "num_rarity_stacks_3" = 0;
    "num_total_cards" = 11;
    oid = "150,1,1";
    rank = 1;
    rewards = "63x 1,0,0; 2x 42,201,0; 6x 42,200,0; 3x 42,200,0";
}```

**Comment by djih** [comment]
@Volcore seems like it could be a serialization issue. Are all of your event property keys strings? Are the values all either numbers of strings?

**Comment by Volcore** [comment]
the values are either NSNumber or NSString. I'm constructing the dict like this:

```  NSMutableDictionary *dict = [[NSMutableDictionary alloc] init];
  for (auto const &mit : params.getMemberNames()) {
    auto key = mit.c_str();
    auto v = params.get(key, "");
    NSObject *obj;
    if (v.isInt()) {
      obj = [NSNumber numberWithInt:v.asInt()];
    } else {
      obj = @(v.asString().c_str());
    }
    [dict setObject:obj forKey:@(key)];
  }
  [[Amplitude instance] logEvent:@(name) withEventProperties:dict];
```

from an internal JSON object.

**Comment by djih** [comment]
@Volcore the code you shared makes sense and seems to encode the values correctly. Is there a way for you to double check that is actually the case?

I tried testing it out myself using the properties you shared from your log:
``` objective-c
NSDictionary *eventProperties = @{
        @"currency_0": @63,
        @"name": @"Gold",
        @"num_rarity_0": @9,
        @"num_rarity_1": @2,
        @"num_rarity_2": @0,
        @"num_rarity_3": @0,
        @"num_rarity_stacks_0": @2,
        @"num_rarity_stacks_1": @1,
        @"num_rarity_stacks_2": @0,
        @"num_rarity_stacks_3": @0,
        @"num_total_cards": @11,
        @"oid": @"150,1,1",
        @"rank": @1,
        @"rewards": @"63x 1,0,0, 2x 42,201,0, 6x 42,200,0, 3x 42,200,0"
    };
[[Amplitude instance] logEvent:@"test event properties" withEventProperties:eventProperties];
```

The SDK was able to send the event successfully (using the new iOS 9 methods), and I'm seeing the properties in Amplitude's user timeline:

![screen shot 2017-08-28 at 5 21 13 pm](https://user-images.githubusercontent.com/4776584/29799005-a4665a38-8c15-11e7-9870-4cc7401373ee.png)

**Comment by Volcore** [comment]
I looked further into it. I've found that I only get the 400 error above if there is a string that contains the ';' character. Reproducer:

```
  auto dict3 = @{
        @"currency_0": @63,
        @"name": @"Gold",
        @"num_rarity_0": @9,
        @"num_rarity_1": @2,
        @"num_rarity_2": @0,
        @"num_rarity_3": @0,
        @"num_rarity_stacks_0": @2,
        @"num_rarity_stacks_1": @1,
        @"num_rarity_stacks_2": @0,
        @"num_rarity_stacks_3": @0,
        @"num_total_cards": @11,
        @"oid": @"150,1,1",
        @"rank": @1,
        @"rewards": @"63x 1,0,0; 2x 42,201,0; 6x 42,200,0; 3x 42,200,0"
    };
  [[Amplitude instance] logEvent:@"param3" withEventProperties:dict3];
```

This will error for me as well (while your example works fine). Worse even, if this happens the uploader is stuck and will not progress -- it will never work again, as it'll try to reupload this event every single time. I've added a check locally to kick out the events if the error above is encountered. In addition, i'll try to avoid semicolons in the strings.

**Comment by djih** [comment]
@Volcore did not realize that I somehow replaced all the semicolons with commas, it's weird that that would break JSON serialization.

Ok then I should be good to release the fix as a new version. Expect to see that either today or tomorrow.

**Comment by djih** [comment]
Still have to add support for SSL pinning so will be delayed

**Comment by djih** [comment]
@Volcore I was able to fix the semicolon checksum issue, so you can remove your local check and continue using semicolons in your strings. Released the fix in [v4.0.0](https://github.com/amplitude/Amplitude-iOS/releases/tag/v4.0.0)
